### ISSUE TITLE
how to click each row of table

### ISSUE THREAD

**Issue by Nitin-clarity** [herbertamukhuma/scrollable_table_view#13]
scrollable_table_veiw library is awesome for scroll horizontal and vertically but I'm not able to click and take a position on each row of table?

**Comment by herbertamukhuma** [comment]
Hello @Nitin-clarity. I have fixed the inability to tap on a row. The function `onTap` below should now work

``` dart
TableViewRow(
  onTap: () {
    print("row tapped");
  },
  height: 60,
  cells: columns.map((column) {
    return TableViewCell(
      child: Text(product[column] ?? ""),
    );
  }).toList(),
)
```

**Comment by herbertamukhuma** [comment]
Am also working on adding the row index as a parameter to the `onTap` function

**Comment by herbertamukhuma** [comment]
I'll proceed to close the issue. If any other issue arises, kindly reopen the issue
