### ISSUE TITLE
ScrollableTableView Issue

### ISSUE THREAD

**Issue by amolk1036** [herbertamukhuma/scrollable_table_view#2]
I have added large data and then its not scrolling (vertically) properly initially it working perfect for few number of rows & column

**Comment by herbertamukhuma** [comment]
Hello @amolk1036, is it possible to share the dataset?

**Comment by herbertamukhuma** [comment]
Received, looking into it

**Comment by amolk1036** [comment]
> Received, looking into it
thanx for reply
Issue is coming in android device on web its working perfectly try adding more data and scroll vertically

**Comment by herbertamukhuma** [comment]
How many records do you have?

**Comment by amolk1036** [comment]
> How many records do you have?

more than 100 rows

**Comment by herbertamukhuma** [comment]
That's expected, apps cannot comfortably handle that amount of data at a time. Find a way of paginating your data so that you have only a few (like 20 - 30) rows to display. Remember this table will load all the rows regardless of whether they are in view or hidden.

**Comment by herbertamukhuma** [comment]
Version 1.0.0 has been published which now supports pagination. Check the README.md file and main.dart example on how to use it.
