### ISSUE TITLE
Example pagination

### ISSUE THREAD

**Issue by caniko** [herbertamukhuma/scrollable_table_view#5]
I have many records, and would apprciate a pagination example.

**Comment by herbertamukhuma** [comment]
By default, the table does not support pagination, but I can implement an example of how you can do that. Will reply on this thread when its done

**Comment by caniko** [comment]
I understand! An afterthough: Shouldn't this be a native feature? Where we provide an argument defining the page-size, pagination is of when no page-size is provided.

**Comment by herbertamukhuma** [comment]
Thanks for the suggestion. I think I can implement that. Will comment when its ready

**Comment by herbertamukhuma** [comment]
Hello @caniko, the pagination request is done on version 1.0.0-beta on pub.dev. You can check out the example on the develop branch main.dart file.

Kindly test and revert on any issue or possible improvement.

**Comment by caniko** [comment]
Thank you! Testing now!

**Comment by herbertamukhuma** [comment]
Hello @caniko, any update? If everything worked properly I'll continue to close the issue and push the new version.

**Comment by herbertamukhuma** [comment]
Version 1.0.0 has been published which now supports pagination. Check the README.md file and main.dart example on how to use it.

**Comment by caniko** [comment]
I tested it yesterday! It works, thank you
