### ISSUE TITLE
No TabController for TabBarView.

### ISSUE THREAD

**Issue by SamadDev** [herbertamukhuma/scrollable_table_view#8]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _BodyBuilder:
No TabController for TabBarView.

When creating a TabBarView, you must either provide an explicit TabController using the "controller" property, or you must ensure that there is a DefaultTabController above the TabBarView.
In this case, there was neither an explicit controller nor a default controller.
The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/Dev/StudioProjects/assignment/lib/test.dart:27:12
When the exception was thrown, this was the stack: 
#0      _TabBarViewState._updateTabController.<anonymous closure> (package:flutter/src/material/tabs.dart:1386:9)
#1      _TabBarViewState._updateTabController (package:flutter/src/material/tabs.dart:1395:6)
#2      _TabBarViewState.didChangeDependencies (package:flutter/src/material/tabs.dart:1416:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4963:11)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)

**Comment by herbertamukhuma** [comment]
Hello @SamadDev , may I see the test.dart file. Also, add the `flutter doctor` output from your console

**Comment by SamadDev** [comment]
test.dart is my file name

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.2130], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.73.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by herbertamukhuma** [comment]
Kindly paste the code of the test file here (only what I need to recreate the issue)

**Comment by SamadDev** [comment]
I have just copied the GitHub example without main have got this error it means the example code is min

**Comment by herbertamukhuma** [comment]
Okay, let me try to reproduce the error, will reach out soon

**Comment by herbertamukhuma** [comment]
I can't downgrade to the flutter version in your `flutter doctor` output, which means that I can't reproduce the error you are having. Additionally, the tab controller issue is a flutter issue and not directly related to this package.
